window.BB_TEXTS = {
    common: {
        appName: 'BlackBears Play',
        appTitle: 'BlackBears Play — Бронирование',
        error: 'Ошибка',
        success: 'Успех',
        mainMenu: 'Главное меню',
        backToMainMenu: 'Вернуться к основным разделам',
        back: 'Назад',
        close: 'Закрыть',
        profile: 'Профиль',
        myBookings: 'Мои брони',
        bookMore: 'Ещё бронь',
        booking: 'Бронь ПК',
        bookingPc: 'Бронь ПК',
        friends: 'Друзья',
        news: 'Новости',
        food: 'Еда',
        games: 'Игры',
        promos: 'Акции',
        supportLabel: 'Поддержка',
        retry: 'Попробовать снова',
        cancel: 'Отмена',
        confirm: 'Подтвердить',
        verify: 'Проверить',
        checking: 'Проверка...',
        topupBalance: 'Пополнить баланс',
        chooseAnotherPc: 'Выбрать другой ПК',
        chooseAnotherTime: 'Выбрать другое время',
        loading: 'Загрузка...',
        currencyRub: '₽',
        guest: 'Гость',
        notSpecified: 'Не указано',
        placeInRanking: 'Место в рейтинге',
        deleteFriend: 'Удалить друга',
        accept: 'Принять',
        reject: 'Отклонить',
        copyLink: 'Копировать ссылку',
        uploadPhoto: 'Загрузить фото',
        delete: 'Удалить',
        done: 'Готово',
    },
    statusBar: {
        guest: 'Гость',
        rankingPlaceTitle: 'Место в рейтинге',
    },
    ui: {
        soundOff: 'Выключить звук',
        soundOn: 'Включить звук',
    },
    inviteBanner: {
        invitedBy: '{sender} приглашает тебя в BlackBears!',
        bonus: '+50₽ бонус за регистрацию',
        closeTitle: 'Закрыть',
        expiresPrefix: 'Действует до: ',
    },
    auth: {
        heroSubtitle: 'Компьютерные клубы',
        barneyName: 'Барни Медведь',
        modeLogin: 'Авторизация',
        modeRegister: 'Регистрация',
        cardTitleLogin: 'Вход',
        cardTitleRegister: 'Регистрация',
        loginIntro: 'Привет, воин! Я Барни — мастер бронирования. Чтобы начать, представься. Введи свой позывной (логин) и пароль.',
        registerIntro: 'Новый воин! Чтобы вступить в ряды BlackBears, заполни анкету.',
        loginPlaceholder: 'Введи логин...',
        passwordPlaceholder: 'Пароль...',
        phonePlaceholder: '+7 (___) ___-__-__',
        emailPlaceholder: 'Email',
        namePlaceholder: 'Твоё имя',
        back: 'Назад',
        login: 'Войти',
        register: 'Регистрация',
        createAccount: 'Создать аккаунт',
        loginRequired: 'Введи свой позывной, воин!',
        passwordRequired: 'Пароль не может быть пустым!',
        loginFailed: 'Не удалось войти. Проверь позывной и пароль.',
        verificationError: 'Ошибка верификации',
        loginMin: 'Логин — минимум 2 символа!',
        passwordMin: 'Пароль — минимум 6 символов!',
        phoneFull: 'Укажи телефон полностью: +7 (XXX) XXX-XX-XX',
        validEmail: 'Нужен корректный email!',
        inviteExpired: 'Приглашение уже использовано или истекло. Зарегистрируйся обычным способом.',
        registerFailed: 'Не удалось создать аккаунт. Попробуй снова.',
        checkingData: 'Проверяю данные...',
    },
    sms: {
        title: 'Подтверждение SMS',
        sentTo: 'Код отправлен на {phone}',
        waiting: 'Ожидание SMS-кода...',
        phoneUnknown: 'твой телефон',
        received: 'Код получен: <strong>{code}</strong>. Нажми «Подтвердить»',
        confirm: 'Подтвердить',
        checking: 'Проверка...',
        sentToYourPhone: 'Код отправлен на твой телефон',
    },
    modals: {
        topupTitle: 'Пополнение баланса',
        bookingConfirmTitle: 'Подтверждение брони',
        friendsTitle: 'Отряд',
        addFriendTitle: 'Добавить друга',
        inviteFriendTitle: 'Пригласить друга',
        avatarTitle: 'Выбрать аватарку',
        smsTitle: 'Подтверждение SMS',
    },
    booking: {
        loading: 'Оформляю бронь...',
        loadingPcs: 'Загружаем ПК...',
        loadingPcsRefresh: 'Обновляем ПК...',
        noPcs: 'Нет данных о ПК',
        mapReception: 'Ресепшен',
        mapBar: 'Бар / кофе',
        legendPicked: 'Выбрано',
        legendFree: 'Свободно',
        legendBusy: 'Занято',
        overlapInline: 'У тебя уже есть активная бронь на этот промежуток времени: {pc} с {start} до {end}. Попробуй после {end}.',
        overlapInlineMultiple: 'У тебя уже есть другие активные брони рядом с этим временем. Ближайший свободный старт — после {end}.',
        overlapBarney: 'У тебя на этот промежуток времени уже забронирован {pc}.\n\nПопробуй после {end}.',
        overlapBarneyMultiple: 'У тебя уже есть другие активные брони рядом с этим временем.\n\nБлижайший свободный старт — после {end}.',
        pastTime: 'Нельзя забронировать на прошедшее время. Выбери дату и время в будущем!',
        occupied: 'Не получилось забронировать этот терминал.\n\nПопробуй соседний свободный ПК или другое время.',
        noBalance: 'Необходимо: {need}₽, у тебя: {have}₽.',
        activationPassword: 'Пароль для активации: {password}\nСообщи его администратору при входе!',
        warnUnderMap: 'У тебя уже есть активная бронь на этот промежуток времени: {pc} с {start} до {end}. Попробуй после {end}.',
    },
    bookingConfirm: {
        title: 'Подтверждение брони',
        cancel: 'Отмена',
        payAndBook: 'Оплатить и забронировать',
    },
    profile: {
        title: 'Вот твоя карта воина, {name}:',
        callsign: 'Позывной: {login}',
        displayName: 'Имя: {name}',
        balance: 'Баланс: {balance}',
        discount: 'Скидка: {discount}%',
        memberId: 'ID в системе: {memberId}',
        avatarHint: 'Нажми чтобы сменить аватарку',
        activeBookings: 'Активные брони ({count})',
        settings: 'Настройки',
        textSpeed: 'Скорость текста Барни',
        typing: 'Печать',
        instant: 'Мгновенно',
        sessions: 'История сессий',
        sessionsDesc: 'Недавние игровые визиты',
        stats: 'Статистика',
        statsDesc: 'Цифры, активность и прогресс',
        logout: 'Выйти',
        logoutDesc: 'Завершить текущую сессию',
        loadingSessions: 'Загружаю историю твоих сражений... ⏳',
        localSessionsLoading: 'Загружаю локальную историю твоих броней...',
        localSessionsEmpty: 'Локальная история броней пока пустая. Как только оформим первую бронь, она появится здесь.',
        localSessionsFound: 'Нашёл {count} записей в локальной истории бронирований:',
        localSessionsLoadError: 'Не удалось загрузить локальную историю броней.\n\nОшибка: {error}',
        bookPcDesc: 'Перейти к новой броне',
        statusActive: 'Активна',
        statusCancelled: 'Отменена',
        statusCompleted: 'Завершена',
        sessionDate: 'Дата',
        sessionDuration: 'Длительность',
        sessionPrice: 'Цена',
        sessionPassword: 'Пароль',
        joinAt: 'в',
        topupProcessing: '⏳ Обработка...',
        topupAdded: 'Пополнено: {amount}₽\nТекущий баланс: 🪙 {balance}₽',
        topupError: 'Ошибка пополнения',
    },
    friends: {
        bookForFriend: 'Забронировать для друга',
        title: 'Отряд',
        subtitle: 'Друзья, заявки и приглашения',
        tabs: {
            friends: 'Друзья',
            outgoing: 'Заявки',
            invitations: 'Приглашения',
        },
        incomingRequests: 'Входящие запросы',
        add: 'Добавить',
        invite: 'Пригласить',
        noFriends: 'У тебя пока нет друзей. Добавь первого товарища!',
        noOutgoing: 'Нет исходящих заявок',
        noInvitations: 'Нет отправленных приглашений',
        sentLabel: 'Отправлено',
        activeStatus: 'Активно',
        usedStatus: 'Использовано',
        expiredStatus: 'Истекло',
        expiresUntil: 'Действует до: {date}',
        gatherSquad: 'Собираю твой отряд: друзья, заявки и приглашения в одном месте.',
        cancelOutgoingConfirm: 'Отменить заявку в друзья для {login}?',
        revokeInviteConfirm: 'Отозвать это приглашение?',
        guestBadge: 'гость',
    },
    invite: {
        title: 'Пригласить друга',
        description: 'Друг перейдёт по ссылке или отсканирует QR — и сразу попадёт в твой отряд!',
        copyLink: 'Копировать ссылку',
        viaVk: 'VK',
        viaTelegram: 'Telegram',
        guestPrefix: 'Гость: {login}',
        linkLabel: 'Ссылка',
    },
    addFriend: {
        title: 'Добавить друга',
        chooseMode: 'Как хочешь добавить товарища?',
        byLogin: 'Найти по логину',
        createGuest: 'Создать гостевой аккаунт',
        sendInvite: 'Отправить приглашение',
        searchPrompt: 'Введи позывной друга:',
        searchPlaceholder: 'Логин друга...',
        search: 'Найти',
        guestPrompt: 'Создам гостевой аккаунт для друга:',
        guestLogin: 'Позывной (логин)',
        guestName: 'Имя друга',
        guestPhone: 'Телефон друга',
        guestEmail: 'Почта друга',
        guestPassword: 'Пароль друга',
        createAndAdd: 'Создать и добавить',
        back: 'Назад',
        close: 'Закрыть',
    },
    avatar: {
        title: 'Выбрать аватарку',
        choosePreset: 'Выбери из готовых:',
        uploadOwn: 'Или загрузи своё фото:',
        upload: 'Загрузить фото',
        uploadHint: 'JPG, PNG, GIF, WebP • Авто-сжатие до 200×200',
        delete: 'Удалить',
        done: 'Готово',
        clickToChange: 'Нажми чтобы сменить аватарку',
    },
    support: {
        title: 'Поддержка',
        greeting: 'Я бот поддержки BlackBears. Задай свой вопрос, и я постараюсь помочь.',
        inputPlaceholder: 'Напиши вопрос...',
        send: 'Отправить',
        back: 'Назад',
        prompts: {
            booking: 'Как забронировать?',
            tariffs: 'Тарифы',
            discounts: 'Скидки',
            addresses: 'Адреса',
            topup: 'Пополнить',
        },
        responses: {
            hello: 'Привет! Чем могу помочь?',
            greetings: 'Здравствуй! Что тебя интересует?',
            bookingHow: 'Нажми "Бронь ПК" в главном меню. Барни проведет тебя через весь процесс: выбери клуб, дату, время, длительность и терминал.',
            booking: 'Бронирование работает через главное меню. Выбери "Бронь ПК" и следуй подсказкам Барни.',
            payment: 'Оплата списывается с баланса при подтверждении бронирования. В демо-режиме можно пополнить баланс через профиль.',
            balance: 'Баланс отображается в статус-баре сверху. Пополнить его можно через профиль или кнопку пополнения.',
            topup: 'Открой профиль и выбери пополнение баланса, либо нажми на кнопку пополнения в доступных сценариях приложения.',
            discount: 'Авторизованные пользователи получают скидку 15% на все тарифы.',
            clubs: 'У нас два клуба: Советская 121 и Астраханская 2А. Выбери раздел клубов или начни бронирование, чтобы увидеть детали.',
            address: 'Наши клубы: Советская 121 и Астраханская 2А.',
            schedule: 'Клубы работают круглосуточно. Бронировать можно на любое удобное время.',
            tariffs: 'Тарифы зависят от зоны и клуба. Есть почасовые тарифы и пакеты, например на 3 часа. Точные цены видны в процессе бронирования.',
            packages: 'Пакеты - это фиксированные наборы часов. Часто они выгоднее, чем обычная почасовая оплата.',
            error: 'Если произошла ошибка, попробуй повторить действие. Если проблема повторяется, напиши подробнее, что именно случилось.',
            broken: 'Опиши подробнее, что не работает. Также попробуй перезагрузить страницу и заново открыть нужный сценарий.',
            restart: 'Перезапуск сессии возвращает приложение к начальному состоянию и помогает при зависших шагах.',
            logout: 'Выход из аккаунта завершает текущую сессию, но данные профиля сохраняются.',
            thanks: 'Всегда пожалуйста! Обращайся, если что.',
            help: 'Я могу помочь с вопросами о бронировании, оплате, тарифах, клубах и работе приложения. Спрашивай.',
            command: 'Напиши свой вопрос, и я постараюсь помочь. Например: "Как забронировать?", "Тарифы", "Скидки".',
        },
        defaults: [
            'Интересный вопрос. Попробуй спросить по-другому или выбери действие в меню.',
            'Не до конца понял запрос. Попробуй уточнить, например про бронь, тарифы, клубы или оплату.',
            'Я бот поддержки и пока знаю не все. Попробуй спросить: "Как забронировать?", "Тарифы", "Скидки".',
        ],
    },
    supportKeywords: {
        hello: ['привет', 'здравствуй'],
        bookingHow: ['как забронировать'],
        booking: ['бронь'],
        payment: ['оплата'],
        balance: ['баланс'],
        topup: ['пополнить'],
        discount: ['скидка'],
        clubs: ['клубы'],
        address: ['адрес'],
        schedule: ['график'],
        tariffs: ['тарифы'],
        packages: ['пакет'],
        error: ['ошибка'],
        broken: ['не работает'],
        restart: ['рестарт'],
        logout: ['выйти'],
        thanks: ['спасибо'],
        help: ['помощь'],
        command: ['команда'],
    },
    wallet: {
        title: 'Твоя казна, воин:',
        balance: 'Баланс: {balance}',
        question: 'Хочешь пополнить или посмотреть историю?',
        topup: 'Пополнить',
        history: 'История',
        loadingHistory: 'Загружаю историю операций...',
        historyUnavailable: 'История операций временно недоступна.\n\nТекущий баланс: {balance}',
        latestOperations: 'Вот последние операции:',
        backToWallet: 'Кошелёк',
        backToWalletDesc: 'Вернуться к экрану баланса',
        historyDesc: 'Посмотреть историю операций',
    },
    ranking: {
        loading: 'Загружаю рейтинг лучших игроков...',
        empty: 'Рейтинг пока пуст. Забронируй ПК и начни подниматься выше.',
        top10: 'Топ-10 игроков наших клубов:',
        fallbackTop: 'Твои лучшие брони:',
        loadError: 'Не удалось загрузить рейтинг. Попробуй позже.',
        yourPlace: 'Твоё место в рейтинге',
        placeLabel: 'Место: #{rank}',
        statusFallback: '—',
        placeUnknown: 'место уточняется',
        youPrefix: 'Ты: {name}',
        visitsLabel: '{count} визитов',
        scoreLabel: '{count} очков',
        combinedLabel: '{score} очков • {visits} визитов',
    },
    topup: {
        title: 'Пополнение баланса',
        description: 'Укажи сумму для пополнения счёта',
        amountPlaceholder: 'Сумма (₽)',
        confirm: 'Пополнить',
        minAmount: 'Минимальная сумма — 10₽',
        maxAmount: 'Максимальная сумма — 100 000₽',
        processing: 'Обработка...',
        error: 'Ошибка пополнения',
    },
    dialogs: {
        mainMenu: {
            bookPcLabel: 'Бронь ПК',
            friendsLabel: 'Друзья',
            friendsDesc: 'Заявки и приглашения',
            newsLabel: 'Новости',
            newsDesc: 'Обновления клуба',
            foodLabel: 'Еда',
            foodDesc: 'Напитки и перекусы',
            gamesLabel: 'Игры',
            gamesDesc: 'Доступные игровые тайтлы',
            bookingsLabel: 'Мои брони',
            bookingsDesc: 'Активные брони',
            promosLabel: 'Акции',
            promosDesc: 'Скидки и бонусы',
            supportLabel: 'Поддержка',
            supportDesc: 'Связь и помощь',
        },
        welcome: {
            withBonus: 'Бонус за приглашение: +{balance}₽ уже на счету.',
            title: 'Добро пожаловать в ряды BlackBears, {name}.',
            accountCreated: 'Твой аккаунт создан. Баланс: {balance}₽.',
            topupAdvice: 'Рекомендую сначала пополнить баланс, а потом уже идти в бой.',
            readyToBook: 'Можно сразу переходить к бронированию.',
            topupActionLabel: 'Пополнить баланс',
            topupActionDesc: 'Добавить средства перед бронью',
            bookingActionLabel: 'Бронь ПК',
            bookingActionDesc: 'Сразу перейти к выбору клуба',
            newsActionLabel: 'Новости',
            newsActionDesc: 'Посмотреть обновления и анонсы',
            supportActionLabel: 'Поддержка',
            supportActionDesc: 'Помощь и связь с клубом',
        },
        clubs: {
            intro: 'Вот наши локации для игры. Выбери клуб, чтобы посмотреть подробности:',
            backLabel: 'Назад',
            backDesc: 'Вернуться в главное меню',
            bookHereLabel: 'Забронировать здесь',
            bookHereDesc: 'Начать бронь для этого клуба',
            toClubListLabel: 'К списку клубов',
            toClubListDesc: 'Вернуться к выбору локации',
            onlinePc: 'Онлайн: {count} ПК',
            offlinePc: 'Оффлайн: {count} ПК',
            bookQuestion: 'Хочешь забронировать ПК в этом клубе?',
            defaultCafeDetails: 'Игровые ПК • Комфортные кресла • Быстрый интернет',
        },
        news: {
            intro: 'Секунду, читаю последние новости нашего VK-паблика...',
            loading: 'Загружаем новости...',
            loadingMore: 'Загружаем еще...',
            openGroup: 'Открыть группу ВКонтакте',
            openPublic: 'Открыть VK-паблик',
            fallback: 'Новости можно открыть прямо в VK-паблике.',
            openPostAria: 'Открыть пост ВКонтакте',
            backLabel: 'Назад',
            backDesc: 'Вернуться на предыдущий экран',
            networkUnavailable: 'Сервер не может подключиться к VK. Открой паблик напрямую.',
            parserUnavailable: 'VK изменил разметку ленты. Открой паблик напрямую.',
            genericFallback: 'Не получилось загрузить посты автоматически. Открой новости прямо в паблике.',
            demo: [
                { date: '5 апреля 2026', text: 'Конкурс ВАЙБКОД. Участвуй и выиграй бесплатные часы игры. Подробности в нашем VK-паблике.' },
                { date: '3 апреля 2026', text: 'Обновление в GameZone. Новые мониторы 280 Гц уже установлены на Советской 121.' },
                { date: '1 апреля 2026', text: 'Ночной тариф действует с 23:00 до 08:00 — скидка 20% на все зоны.' },
                { date: '28 марта 2026', text: 'Барни напоминает: бронируй ПК заранее, чтобы не ждать в очереди в выходные.' },
            ],
        },
        food: {
            intro: 'Вот наше меню. Выбирай, что взять во время игры:',
            tableName: 'Название',
            tableSize: 'Объём',
            tablePrice: 'Цена',
            backLabel: 'Назад',
            backDesc: 'Вернуться на предыдущий экран',
        },
        games: {
            intro: 'У нас установлено {count} игр. Все доступны на любом ПК:',
            backLabel: 'Назад',
            backDesc: 'Вернуться на предыдущий экран',
        },
        promos: {
            intro: 'У нас есть несколько акций. Выбирай подходящую:',
            backLabel: 'Назад',
            backDesc: 'Вернуться в главное меню',
        },
    },
    orders: {
        barneyCatalog: 'Выбирай позиции, я соберу корзину и оформлю заказ.',
        barneyOrders: 'Сейчас покажу твои заказы.',
        tabs: {
            catalog: 'Каталог',
            orders: 'Заказы',
            active: 'Активные',
            history: 'История',
        },
        categoriesAria: 'Категории меню',
        searchPlaceholder: 'Найти напиток или перекус',
        nothingFound: 'Ничего не нашли. Попробуй другую категорию или запрос.',
        cart: 'Корзина',
        empty: 'Пусто',
        checkout: 'Оформить',
        decrease: 'Уменьшить',
        increase: 'Добавить',
        cartEmpty: 'Корзина пустая',
        products: 'Товары',
        deliveryToPc: 'Доставка за ПК',
        total: 'Итого',
        club: 'Клуб',
        detectClubAutomatically: 'Определить автоматически',
        pickup: 'Самовывоз',
        deliverWithFee: 'Доставить за ПК +100₽',
        paymentMethods: {
            balance: 'Баланс',
            cardApp: 'Карта в приложении',
            sbpApp: 'СБП',
            cash: 'Наличка',
            terminalCard: 'Терминал',
            terminalQr: 'QR на кассе',
        },
        tablePlaceholderDelivery: 'ПК для доставки, например PC09',
        tablePlaceholderPickup: 'Стол или комментарий к выдаче',
        commentPlaceholder: 'Комментарий к заказу',
        submitOrder: 'Оформить заказ',
        clubFallback: 'Клуб {id}',
        loadingOrders: 'Загружаю заказы...',
        noActiveOrders: 'Активных заказов нет',
        emptyHistory: 'История заказов пустая',
        openDetails: 'Открыть детали',
        orderTitle: 'Заказ #{id}',
        delivery: 'Доставка',
        clubNotSpecified: 'не указан',
        pickupType: 'Самовывоз',
        deliveryType: 'Доставка за ПК',
        payment: 'Оплата',
        code: 'Код',
        createdAt: 'Оформлен: {date}',
        commentPrefix: 'Комментарий: {text}',
        completedAt: 'Завершен: {date}',
        backToOrders: 'Вернуться к заказам',
        tipsTitle: 'Оставить чаевые',
        customSumPlaceholder: 'Другая сумма',
        tipButton: 'Оставить {amount}₽',
        tipsAdded: 'Чаевые добавлены. Спасибо!',
        submitError: 'Не получилось оформить заказ.',
        payByBalanceTitle: 'Оплата балансом',
        payByBalanceQuestion: 'Списать {total}₽ с баланса?',
        confirmWriteoff: 'Подтвердить списание',
        payByCardTitle: 'Карта в приложении',
        cardNumber: 'Номер карты',
        cardName: 'Имя на карте',
        payButton: 'Оплатить {total}₽',
        sbpTitle: 'СБП',
        sbpChooseBank: 'Выбери банк и продолжи.',
        sbpOpenBank: 'Открыть банк',
        backToOrder: 'К заказу',
        backToOrderDesc: 'Открыть заказ без оплаты',
        cardValidationError: 'Проверь номер карты, срок, CVC и имя.',
        openingBank: 'Открываем банк...',
        paymentConfirmed: 'Оплата подтверждена, возвращаемся в приложение...',
        processing: 'Обрабатываем...',
        status: {
            new: 'Новый',
            awaitingPickup: 'Ожидает выдачи',
            delivering: 'Доставляется',
            completed: 'Завершен',
            cancelled: 'Отменен',
        },
        paymentStatus: {
            pending: 'Оплата ожидается',
            paid: 'Оплачено',
            payOnPickup: 'Оплата на месте',
        },
        paymentMethodLabel: {
            balance: 'Баланс',
            cardApp: 'Карта в приложении',
            sbpApp: 'СБП',
            cash: 'Наличными при выдаче',
            terminalCard: 'Картой на терминале',
            terminalQr: 'QR на кассе',
        },
        navBack: 'Назад',
        navBackDesc: 'Вернуться на предыдущий экран',
    },
    errors: {
        topupMin: 'Минимальная сумма — 10₽',
        topupMax: 'Максимальная сумма — 100 000₽',
        topupFailed: 'Ошибка пополнения',
        parserUnavailable: 'VK изменил разметку ленты. Открой паблик напрямую.',
        networkUnavailable: 'Сервер не может подключиться к VK. Открой паблик напрямую.',
    },
    app: {
        initLog: 'BlackBears Play — Инициализация...',
        readyLog: 'Приложение готово к работе',
    },
    catalog: {
        food: {
            'Газ.вода': [
                { id: 'cool-cola-033', category: 'Газ.вода', name: 'COOL COLA', size: '0,33 л', price: 80 },
                { id: 'cool-cola-1', category: 'Газ.вода', name: 'COOL COLA', size: '1 л', price: 140 },
                { id: 'fancy-033', category: 'Газ.вода', name: 'FANCY', size: '0,33 л', price: 80 },
                { id: 'street-033', category: 'Газ.вода', name: 'STREET', size: '0,33 л', price: 80 },
                { id: 'tonic-033', category: 'Газ.вода', name: 'TONIC', size: '0,33 л', price: 80 },
                { id: 'kvass-ochakovo-05', category: 'Газ.вода', name: 'КВАС ОЧАКОВО', size: '0,5 л', price: 80 },
                { id: 'svyatoy-istochnik-05', category: 'Газ.вода', name: 'СВЯТОЙ ИСТОЧНИК', size: '0,5 л', price: 80 },
                { id: 'water-05', category: 'Газ.вода', name: 'ВОДА', size: '0,5 л', price: 65 },
            ],
            'Энергетики': [
                { id: 'gorilla-045', category: 'Энергетики', name: 'GORILLA (все вкусы)', size: '0,45 л', price: 110 },
                { id: 'shpilli-villi-05', category: 'Энергетики', name: 'ШПИЛЛИ ВИЛЛИ', size: '0,5 л', price: 80 },
                { id: 'varan-05', category: 'Энергетики', name: 'VARAN', size: '0,5 л', price: 80 },
            ],
            'Еда': [
                { id: 'snickers-30', category: 'Еда', name: 'SNICKERS', size: '30 гр', price: 80 },
                { id: 'bounty-30', category: 'Еда', name: 'BOUNTY', size: '30 гр', price: 80 },
                { id: 'twix-30', category: 'Еда', name: 'TWIX', size: '30 гр', price: 80 },
                { id: 'mars-30', category: 'Еда', name: 'MARS', size: '30 гр', price: 80 },
                { id: 'mms-40', category: 'Еда', name: "M&M'S", size: '40 гр', price: 85 },
            ],
            'Горячее (Астраханская)': [
                { id: 'tea-02', category: 'Горячее (Астраханская)', name: 'ЧАЙ', size: '0,2 л', price: 70 },
                { id: 'coffee-nespresso-02', category: 'Горячее (Астраханская)', name: 'КОФЕ НЕСПРЕССО', size: '0,2 л', price: 100 },
                { id: 'coffee-dolche-gusto-03', category: 'Горячее (Астраханская)', name: 'КОФЕ DOLCHE GUSTO', size: '0,3 л', price: 140 },
                { id: 'hot-dog', category: 'Горячее (Астраханская)', name: 'HOT DOG', size: '-', price: 199 },
            ],
        },
        games: [
            { name: 'Apex Legends', icon: 'assets/games/apex-legends.svg' },
            { name: 'CS 2', icon: 'assets/games/cs-2.svg' },
            { name: 'Dota 2', icon: 'assets/games/dota-2.svg' },
            { name: 'Dota Underlords', icon: 'assets/games/dota-underlords.svg' },
            { name: 'Dead by Daylight', icon: 'assets/games/dead-by-daylight.svg' },
            { name: 'Escape from Tarkov', icon: 'assets/games/escape-from-tarkov.svg' },
            { name: 'Warframe', icon: 'assets/games/warframe.svg' },
            { name: 'Warface', icon: 'assets/games/warface.svg' },
            { name: 'Fortnite', icon: 'assets/games/fortnite.svg' },
            { name: 'League of Legends', icon: 'assets/games/league-of-legends.svg' },
            { name: 'Overwatch 2', icon: 'assets/games/overwatch-2.svg' },
            { name: 'PUBG', icon: 'assets/games/pubg.svg' },
            { name: 'Genshin Impact', icon: 'assets/games/genshin-impact.svg' },
            { name: 'GTA V', icon: 'assets/games/gta-v.svg' },
            { name: 'Мир танков', icon: 'assets/games/world-of-tanks.svg' },
            { name: 'Мир кораблей', icon: 'assets/games/world-of-warships.svg' },
            { name: 'War Thunder', icon: 'assets/games/war-thunder.svg' },
            { name: 'Rust', icon: 'assets/games/rust.svg' },
            { name: 'Rainbow Six Siege', icon: 'assets/games/rainbow-six-siege.svg' },
            { name: 'Rocket League', icon: 'assets/games/rocket-league.svg' },
            { name: 'Valorant', icon: 'assets/games/valorant.svg' },
            { name: 'Hearthstone', icon: 'assets/games/hearthstone.svg' },
        ],
        promos: [
            {
                title: 'День рождения',
                description: 'Скидка 50% на день рождения.',
                details: 'Скидка единоразовая. Действует 3 дня до и 3 дня после дня рождения.',
                iconPath: './ui%20kit/icon/bulk/cake.svg',
            },
            {
                title: 'Оставь отзыв',
                description: '100₽ на баланс за отзыв.',
                details: 'Оставь отзыв на любом геосервисе и получи 100₽ на баланс.',
                iconPath: './ui%20kit/icon/bulk/star.svg',
            },
            {
                title: 'Дневной мишка',
                description: '3 часа = 200₽ в GameZone.',
                details: 'Только будни. До 18 лет. Астраханская: 09:00-15:00. Советская: 09:00-17:00.',
                iconPath: './ui%20kit/icon/bulk/gift.svg',
            },
        ],
    },
    config: {
        phrases: {
            greeting: [
                'Привет, воин! Я Барни — мастер бронирования. Готов к битве?',
                'Здарова! Барни на связи. Куда направимся?',
                'Добро пожаловать в таверну! Чем могу помочь?',
            ],
        },
    },
};

window.BBText = {
    get(path, fallback = null) {
        const value = String(path || '').split('.').reduce((node, key) => {
            return node && Object.prototype.hasOwnProperty.call(node, key) ? node[key] : null;
        }, window.BB_TEXTS);
        return value == null ? fallback : value;
    },

    t(path, params = {}, fallback = null) {
        const value = this.get(path, fallback ?? String(path || ''));
        const text = typeof value === 'string' ? value : String(fallback ?? path ?? '');
        return text.replace(/\{(\w+)\}/g, (_, key) => {
            return Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : '';
        });
    },

    pick(path, fallback = '') {
        const value = this.get(path, null);
        if (Array.isArray(value) && value.length > 0) {
            return value[Math.floor(Math.random() * value.length)];
        }
        return fallback;
    },
};
